import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    padding: 16,
  },
  title: {
    fontSize: 40,
    fontWeight: "bold",
    fontFamily: "Inter",
    alignSelf: "center",
    marginBottom: 10,
  },
  topControls: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
    marginBottom: 10,
    zIndex: 100,
  },
  leftControls: {
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
  },
  addButton: {
    flexDirection: "row",
    backgroundColor: "#D9D9D9",
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 6,
    alignItems: "center",
    height: 40,
  },
  addButtonText: {
    color: "#000",
    fontSize: 14,
    marginLeft: 10,
  },
  dropdown: {
    height: 10,
    maxHeight: "100%",
    borderColor: "#D9D9D9",
    backgroundColor: "#D9D9D9",
    paddingHorizontal: 10,
    marginBottom: 9,
    fontSize: 14,
  },
  dropdownContainer: {
    borderColor: "#D9D9D9",
    backgroundColor: "#D9D9D9",
    width: "100%",
  },
  searchInput: {
    borderWidth: 1,
    borderColor: "#D9D9D9",
    backgroundColor: "#D9D9D9",
    borderRadius: 6,
    paddingHorizontal: 10,
    height: 40,
    minWidth: 370,
  },
  tableHeader: {
    backgroundColor: "#213594",
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderColor: "#ccc",
    backgroundColor: "#ccc",
  },
  cellHeader: {
    flex: 1,
    color: "#fff",
    fontWeight: "bold",
    paddingVertical: 10,
    textAlign: "center",
    borderRightWidth: 1,
    borderColor: "#ccc",
  },
  cell: {
    flex: 1,
    textAlign: "center",
    paddingVertical: 8,
    borderRightWidth: 1,
    borderColor: "#ccc",
    backgroundColor: "#FBFBFB",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.3)",
    justifyContent: "center",
    alignItems: "center",
  },
  sectionTitleBox: {
    width: "95%",
    borderWidth: 1,
    padding: 13,
    borderWidth: 2,
    borderColor: "#00188D",
    borderRadius: 10,
    backgroundColor: "#00188D",
    marginBottom: 10,
    alignSelf: "center",
  },
  sectionTitleText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
    fontFamily: "Inter",
    marginRight: 700,
  },
  formContainer: {
    height: 420,
    width: "95%",
    borderWidth: 1,
    borderColor: "#ccc",
    padding: 15,
    overflow: "scroll",
    backgroundColor: "#FFFFFF",
    alignSelf: "center",
    marginBottom: 10,
  },
  label: {
    fontSize: 13,
    color: "#000",
    fontFamily: "Inter",
    marginTop: 10,
    fontWeight: "bold",
  },
  label2: {
    fontSize: 10,
    color: "#000",
    fontFamily: "Inter",
    marginTop: 3,
    marginLeft: 10,
  },
  input: {
    width: "100%",
    borderWidth: 2,
    borderColor: "#D9D9D9",
    padding: 10,
    marginTop: 10,
    borderRadius: 12,
    minHeight: 44,
  },
  radioContainer: {
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
    marginVertical: 0,
    marginBottom: 10,
  },
  radioOuterCircle: {
    height: 15,
    width: 15,
    borderWidth: 2,
    marginRight: 15,
    borderRadius: 12,
    borderColor: "#D9D9D9",
    alignItems: "center",
    justifyContent: "center",
  },
  radioOuterCircleSelected: {
    backgroundColor: "#00188D",
  },
  radioLabel: {
    fontSize: 16,
  },
  radioInnerCircle: {
    height: 12,
    width: 12,
    borderRadius: 6,
    backgroundColor: "#00188D",
  },
  radioButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  pickerWrapper: {
    borderWidth: 2,
    borderColor: "#D9D9D9",
    borderRadius: 12,
    backgroundColor: "#FFFFFF",
    minHeight: 44,
    marginBottom: 10,
  },
  errorInput: {
    borderColor: "red",
    borderWidth: 1,
  },
  errorText: {
    color: "red",
    fontSize: 10,
    marginBottom: 5,
  },
  dropdown: {
    marginTop: 10,
    borderColor: "#D9D9D9",
    borderWidth: 2,
    borderRadius: 12,
    paddingHorizontal: 10,
    backgroundColor: "#FFFFFF",
    minHeight: 44,
  },
  dropdownContainer: {
    borderColor: "#D9D9D9",
    backgroundColor: "#FFFFFF",
    maxHeight: 150,
    borderWidth: 2,
    borderRadius: 12,
    width: "100%",
  },
  number: {
    flexDirection: "row",
    alignItems: "center",
    borderColor: "#D9D9D9",
    borderWidth: 2,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 12,
    backgroundColor: "#FFFFFF",
    minHeight: 44,
  },
  prefix: {
    marginRight: 8,
    fontSize: 16,
    color: "#333",
  },
  phoneInput: {
    flex: 1,
    fontSize: 16,
  },
  buttonContainer: {
    marginTop: 10,
    alignItems: "right",
  },
  button: {
    position: "center",
    right: 20,
    bottom: 20,
    backgroundColor: "#00188D",
    paddingVertical: 13,
    paddingHorizontal: 30,
    borderRadius: 8,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
  },
  buttonRight: {
    marginLeft: 250,
  },
  buttonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
  },
  buttonRow: {
    flexDirection: "row",
    justifyContent: "justify",
  },
  container: {
    padding: 16,
  },
  title: {
    fontSize: 40,
    fontWeight: "bold",
    fontFamily: "Inter",
    alignSelf: "center",
    marginBottom: 10,
  },
  topControls: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
    marginBottom: 10,
    zIndex: 100,
  },
  leftControls: {
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
  },
  addButton: {
    flexDirection: "row",
    backgroundColor: "#D9D9D9",
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 6,
    alignItems: "center",
    height: 40,
  },
  addButtonText: {
    color: "#000",
    fontSize: 14,
    marginLeft: 10,
  },
  dropdown: {
    height: 10,
    maxHeight: "100%",
    borderColor: "#D9D9D9",
    backgroundColor: "#D9D9D9",
    paddingHorizontal: 10,
    marginBottom: 9,
    fontSize: 14,
  },
  dropdownContainer: {
    borderColor: "#D9D9D9",
    backgroundColor: "#D9D9D9",
    width: "100%",
  },
  searchInput: {
    borderWidth: 1,
    borderColor: "#D9D9D9",
    backgroundColor: "#D9D9D9",
    borderRadius: 6,
    paddingHorizontal: 10,
    height: 40,
    minWidth: 370,
  },
  tableHeader: {
    backgroundColor: "#213594",
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderColor: "#ccc",
    backgroundColor: "#ccc",
  },
  cellHeader: {
    flex: 1,
    color: "#fff",
    fontWeight: "bold",
    paddingVertical: 10,
    textAlign: "center",
    borderRightWidth: 1,
    borderColor: "#ccc",
  },
  cell: {
    flex: 1,
    textAlign: "center",
    paddingVertical: 8,
    borderRightWidth: 1,
    borderColor: "#ccc",
    backgroundColor: "#FBFBFB",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.3)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "#fff",
    padding: 20,
    borderRadius: 10,
    width: "80%",
    height: "95%",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 10,
  },
  modalInput: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 6,
    padding: 10,
    marginVertical: 6,
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginTop: 10,
    alignItems: "right",
  },
  modalButtonLeft: {
    position: "center",
    height: 35,
    right: 20,
    bottom: 20,
    backgroundColor: "#D9D9D9",
    paddingVertical: 5,
    paddingHorizontal: 20,
    borderRadius: 8,
    elevation: 2, // Adds Android shadow
    shadowColor: "#000", // iOS shadow
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    marginTop: 10,
    marginRight: 650,
  },
  modalButtonRight: {
    position: "center",
    height: 35,
    right: 20,
    bottom: 20,
    backgroundColor: "#00188D",
    paddingVertical: 5,
    paddingHorizontal: 30,
    borderRadius: 8,
    elevation: 2, // Adds Android shadow
    shadowColor: "#000", // iOS shadow
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    marginTop: 10,
  },
  buttonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
  },

  pickerContainer: {
    backgroundColor: "#fff",
    borderRadius: 10,
    overflow: "hidden",
    elevation: 10,
    padding: 5,
  },
  webContainer: {
    height: "100%",
    width: "100%",
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
  },
  webBorder: {
    height: 50,
    width: "95%",
    borderWidth: 1,
    borderColor: "#ccc",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: -4,
    borderColor: "#00188D",
    borderRadius: 7,
    backgroundColor: "#00188D",
    marginTop: 50,
  },
  fieldRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
    gap: 30,
  },
  fieldColumn: {
    flex: 1,
    minWidth: 1, // Prevents overflow
  },
  chip: {
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 20,
    alignSelf: "center",
    marginTop: -4,
  },
  chipText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 14,
  },
});
  